server:
  port: 8080
spring:
  application:
    name: ArkBase
  profiles:
    active: dev
  liquibase:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    properties:
      hibernate:
        connection:
          provider-disables-autocommit: true
        format-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: Hikari
      auto-commit: false

---

spring.profiles: dev
logging:
  level:
    root: debug
    net.ttddyy.dsproxy.listener: debug

---

spring.profiles: prod
logging:
  level:
    root: info
    net.ttddyy.dsproxy.listener: info