--liquibase formatted sql

--changeset minouni:1
CREATE TABLE operators (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code_name VARCHAR(255) NOT NULL UNIQUE,
  archetype VARCHAR(255) NOT NULL,
  rarity VARCHAR(255) NOT NULL,
  trait VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  attack_type VARCHAR(255) NOT NULL,
  CONSTRAINT pk_operators PRIMARY KEY (id)
);
