--liquibase formatted sql

--changeset minouni:1
CREATE TABLE skills (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL,
  sp_cost INTEGER NOT NULL,
  level INTEGER NOT NULL,
  mastery INTEGER NOT NULL,
  recovery_type VARCHAR(255) NOT NULL,
  activation_type VARCHAR(255) NOT NULL,
  duration INTEGER NOT NULL,
  CONSTRAINT pk_skills PRIMARY KEY (id)
);

CREATE TABLE skills_materials (
  material_id INTEGER NOT NULL,
  skill_id INTEGER NOT NULL,
  CONSTRAINT pk_skills_materials PRIMARY KEY (material_id, skill_id)
);

ALTER TABLE skills_materials
ADD CONSTRAINT fk_skimat_on_material FOREIGN KEY (material_id) REFERENCES materials (id);

ALTER TABLE skills_materials
ADD CONSTRAINT fk_skimat_on_skill FOREIGN KEY (skill_id) REFERENCES skills (id);